apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2  # You can adjust this based on your needs
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: REPOSITORY_TAG  # This will be replaced by the actual ECR image URL during deployment
        ports:
        - containerPort: 80
